/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GerencialImprimirRouteImport } from './routes/gerencial-imprimir'
import { Route as GerencialRouteImport } from './routes/gerencial'
import { Route as ApontarRouteImport } from './routes/apontar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportOrderIdRouteImport } from './routes/report.$orderId'
import { Route as LoadingOrderIdRouteImport } from './routes/loading.$orderId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GerencialImprimirRoute = GerencialImprimirRouteImport.update({
  id: '/gerencial-imprimir',
  path: '/gerencial-imprimir',
  getParentRoute: () => rootRouteImport,
} as any)
const GerencialRoute = GerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApontarRoute = ApontarRouteImport.update({
  id: '/apontar',
  path: '/apontar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportOrderIdRoute = ReportOrderIdRouteImport.update({
  id: '/report/$orderId',
  path: '/report/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingOrderIdRoute = LoadingOrderIdRouteImport.update({
  id: '/loading/$orderId',
  path: '/loading/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apontar': typeof ApontarRoute
  '/gerencial': typeof GerencialRoute
  '/gerencial-imprimir': typeof GerencialImprimirRoute
  '/login': typeof LoginRoute
  '/loading/$orderId': typeof LoadingOrderIdRoute
  '/report/$orderId': typeof ReportOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apontar': typeof ApontarRoute
  '/gerencial': typeof GerencialRoute
  '/gerencial-imprimir': typeof GerencialImprimirRoute
  '/login': typeof LoginRoute
  '/loading/$orderId': typeof LoadingOrderIdRoute
  '/report/$orderId': typeof ReportOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apontar': typeof ApontarRoute
  '/gerencial': typeof GerencialRoute
  '/gerencial-imprimir': typeof GerencialImprimirRoute
  '/login': typeof LoginRoute
  '/loading/$orderId': typeof LoadingOrderIdRoute
  '/report/$orderId': typeof ReportOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apontar'
    | '/gerencial'
    | '/gerencial-imprimir'
    | '/login'
    | '/loading/$orderId'
    | '/report/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apontar'
    | '/gerencial'
    | '/gerencial-imprimir'
    | '/login'
    | '/loading/$orderId'
    | '/report/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apontar'
    | '/gerencial'
    | '/gerencial-imprimir'
    | '/login'
    | '/loading/$orderId'
    | '/report/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApontarRoute: typeof ApontarRoute
  GerencialRoute: typeof GerencialRoute
  GerencialImprimirRoute: typeof GerencialImprimirRoute
  LoginRoute: typeof LoginRoute
  LoadingOrderIdRoute: typeof LoadingOrderIdRoute
  ReportOrderIdRoute: typeof ReportOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencial-imprimir': {
      id: '/gerencial-imprimir'
      path: '/gerencial-imprimir'
      fullPath: '/gerencial-imprimir'
      preLoaderRoute: typeof GerencialImprimirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencial': {
      id: '/gerencial'
      path: '/gerencial'
      fullPath: '/gerencial'
      preLoaderRoute: typeof GerencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apontar': {
      id: '/apontar'
      path: '/apontar'
      fullPath: '/apontar'
      preLoaderRoute: typeof ApontarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$orderId': {
      id: '/report/$orderId'
      path: '/report/$orderId'
      fullPath: '/report/$orderId'
      preLoaderRoute: typeof ReportOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading/$orderId': {
      id: '/loading/$orderId'
      path: '/loading/$orderId'
      fullPath: '/loading/$orderId'
      preLoaderRoute: typeof LoadingOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApontarRoute: ApontarRoute,
  GerencialRoute: GerencialRoute,
  GerencialImprimirRoute: GerencialImprimirRoute,
  LoginRoute: LoginRoute,
  LoadingOrderIdRoute: LoadingOrderIdRoute,
  ReportOrderIdRoute: ReportOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
