/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportOrderIdRouteImport } from './routes/report.$orderId'
import { Route as LoadingOrderIdRouteImport } from './routes/loading.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportOrderIdRoute = ReportOrderIdRouteImport.update({
  id: '/report/$orderId',
  path: '/report/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingOrderIdRoute = LoadingOrderIdRouteImport.update({
  id: '/loading/$orderId',
  path: '/loading/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loading/$orderId': typeof LoadingOrderIdRoute
  '/report/$orderId': typeof ReportOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loading/$orderId': typeof LoadingOrderIdRoute
  '/report/$orderId': typeof ReportOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loading/$orderId': typeof LoadingOrderIdRoute
  '/report/$orderId': typeof ReportOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loading/$orderId' | '/report/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loading/$orderId' | '/report/$orderId'
  id: '__root__' | '/' | '/loading/$orderId' | '/report/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadingOrderIdRoute: typeof LoadingOrderIdRoute
  ReportOrderIdRoute: typeof ReportOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$orderId': {
      id: '/report/$orderId'
      path: '/report/$orderId'
      fullPath: '/report/$orderId'
      preLoaderRoute: typeof ReportOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading/$orderId': {
      id: '/loading/$orderId'
      path: '/loading/$orderId'
      fullPath: '/loading/$orderId'
      preLoaderRoute: typeof LoadingOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadingOrderIdRoute: LoadingOrderIdRoute,
  ReportOrderIdRoute: ReportOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
